var DB_NEWS = [
  "https://www.bloomberg.com",
  "https://www.wsj.com",
  "https://abcnews.go.com",
  "https://www.cbsnews.com",
  "https://www.telegraph.co.uk",
  "https://www.dailymail.co.uk",
  "https://www.thehill.com",
  "https://www.theatlantic.com",
  "https://www.newyorker.com",
  "https://www.time.com",
  "https://www.wired.com",
  "https://www.ars Technica.com",
  "https://www.cnet.com",
  "https://www.wired.co.uk",
  "https://www.marketwatch.com",
  "https://www.bloomberg.com/markets",
  "https://www.wsj.com/markets",
  "https://www.bloomberg.com/politics",
  "https://www.thehill.com",
  "https://www.france24.com",
  "https://www.bbc.com/news/world/americas",
  "https://www.bbc.com/news/world/middle-east",
  "https://www.nature.com/news",
  "https://www.popsci.com",
  "https://www.newscientist.com",
  "https://www.discovermagazine.com",
  "https://www.science daily.com",
  "https://www.esa.int/News",
  "https://www.healthline.com",
  "https://www.mayoclinic.org",
  "https://www.cdc.gov",
  "https://www.medicalnewstoday.com",
];
